version: "3.6"

services:
  application:
    container_name: application
    build:
      context: ./application
      dockerfile: Dockerfile.prod
    networks:
      - fcnetwork
    volumes:
      - ./application:/usr/src/application
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - database
    entrypoint: dockerize -wait tcp://database:3306 -timeout 30s docker-entrypoint.sh
    command: node .

  database:
    container_name: "database"
    image: "mysql"
    command: "--innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password"
    restart: "always"
    tty: true
    volumes:
      - ./database:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fcnetwork

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - application
    networks:
      - fcnetwork

networks:
  fcnetwork:
    driver: bridge
