version: "3"

services:
  application:
    container_name: application
    build:
      context: ./application
      dockerfile: Dockerfile.prod
    networks:
      - fcnetwork
    volumes:
      - ./application:/usr/src/application
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - database
    entrypoint: dockerize -wait tcp://database:3306 -timeout 30s docker-entrypoint.sh
    command: node .

  database:
    image: "mysql:latest"
    command: "--innodb-use-native-aio=0"
    container_name: "database"
    restart: "always"
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fcnetwork

  # nginx:

networks:
  fcnetwork:
    driver: bridge
